### ISSUE TITLE
Assignment 2 Submission

### ISSUE THREAD

**Issue by domanhtien2011** [domanhtien2011/chatty#1]
Hi Coder School, I've just finished my assignment. Although it looks terrible, and lacks of few functionalities, I think I have learned many new lessons through it. Please let me know if you have any feedbacks so that I can improve myself. Thanks again and have a nice day.

cc @coderschoolreview

**Comment by hoksilato** [comment]
Hi @domanhtien2011, nice work with your homework :+1:

The goals of this homework are:
- to know how to implement authentication from scratch in Rails with the help of the `has_secure_password` class method and the `brypt` gem (while understanding what they do under the hood)
- to design a more complex schema for a web app and be more familiar with ActiveRecord API such as custom foreign keys for `belongs_to`/`has_many`, using `has_many :through` and building more advanced queries by chaining `where`, `order`, and `merge`
- to build more complex forms in views that involve multiple models.

## Quick review:
- Great job with validation on sign up and new message form, especially `email` validity part.
- Nice and clean custom routes.
- Good work with `helper_method :current_user, :user_signed_in?`.
- Good work with checking whether user signed in or not before allow them to add friend and send message.
- Good work with associations between models.
- Good work with the logic that not allow add friend and send message to yourself.

## Suggestions
- Should not include friends in user list for adding friend.
- You can define `before_action :require_login` in `application_controller.rb` so that it'll be effective whole your app. And with the actions that don't need it, use `skip_before_action`.

Congrats again on the submission. Everyone has limited time; it's good to see you finished all required functionalities. Keep your good work :100:. Let us know if you have any feedback.

**Comment by domanhtien2011** [comment]
Thank you so much for your feedback. I will take note your feedback and try to improve my Rails skill in the future. Thank you for your time again, I know you guys are very busy. Have a good night. ^^
